    steps:
      # ... (suas etapas anteriores)

      - name: Compute vars
        id: vars
        shell: pwsh
        run: |
          $short = $env:GITHUB_SHA.Substring(0,7)
          "short_sha=$short" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Make ZIP artifact
        shell: pwsh
        run: |
          $zip = "SimulIDE-MSVC-${{ steps.vars.outputs.short_sha }}.zip"
          Compress-Archive -Path "${{ steps.outdir.outputs.dir }}\*" -DestinationPath "$zip"
          "ZIP=$zip" | Out-File -FilePath $env:GITHUB_OUTPUT -Append

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimulIDE-MSVC
          path: ./*.zip
          if-no-files-found: error

      - name: Create GitHub Release (on tags)
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: ./*.zip
          generate_release_notes: true
