name: Windows Qt Build (SimulIDE MinGW)

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  workflow_dispatch:
    inputs:
      version:
        description: "Versão manual (ex.: v2.0.0-RC1)"
        required: false
        type: string
      publish_release:
        description: "Publicar release?"
        required: true
        default: true
        type: boolean

permissions:
  contents: write

jobs:
  build-win-mingw:
    runs-on: windows-latest
    env:
      QT_VERSION: '5.15.2'
      QT_ARCH: 'win64_mingw81'

    steps:
      # --- Checkout ----------------------------------------------------------
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # --- Instala Qt --------------------------------------------------------
      - name: Install Qt (5.15.2 MinGW)
        uses: jurplel/install-qt-action@v4
        with:
          version: ${{ env.QT_VERSION }}
          host: windows
          target: desktop
          arch: ${{ env.QT_ARCH }}
          archives: 'qtbase qtsvg qtmultimedia qtserialport qttools'
          cache: true

      # --- Define versão -----------------------------------------------------
      - name: Compute version
        shell: pwsh
        run: |
          if ("${{ github.event_name }}" -eq "workflow_dispatch" -and "${{ inputs.version }}") {
            $ver = "${{ inputs.version }}"
          } elseif ("${{ github.ref }}".StartsWith("refs/tags/")) {
            $ver = "${{ github.ref_name }}"
          } else {
            $ver = "dev${{ github.run_number }}"
          }
          $ver = $ver -replace '[^0-9A-Za-z._-]', ''
          "APP_VER=$ver" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host ">> Versão definida: $ver"

      # --- Configuração (qmake) ---------------------------------------------
      - name: Configure project (qmake MinGW)
        shell: pwsh
        run: |
          cd build_XX
          qmake -spec win32-g++ "CONFIG+=release" `
                "VERSION=${{ env.APP_VER }}" `
                "DESTDIR=executables/SimulIDE_${{ env.APP_VER }}" `
                "TARGET=simulide"
          if ($LASTEXITCODE -ne 0) { throw "qmake falhou" }

      # --- Garante pasta de saída -------------------------------------------
      - name: Ensure executables directory exists
        shell: pwsh
        run: |
          New-Item -ItemType Directory -Force -Path "build_XX\executables\SimulIDE_${{ env.APP_VER }}" | Out-Null

      # --- Remove linhas quebradas de tradução ------------------------------
      - name: Patch Makefile.Release (remove lrelease/move)
        shell: pwsh
        run: |
          $mf = "build_XX\\Makefile.Release"
          if (Test-Path $mf) {
            $c = Get-Content $mf -Raw
            $c = $c -replace '(?m)^.*\blrelease\b .*$', '# lrelease removido'
            $c = $c -replace '(?m)^.*\bmove\b .*\.qm.*$', '# move removido'
            Set-Content $mf $c -Encoding UTF8
            Write-Host ">> Linhas lrelease/move removidas"
          }

      # --- (Debug opcional) Mostra DESTDIR/TARGET ---------------------------
      - name: Debug Makefile (DESTDIR/TARGET)
        shell: pwsh
        run: |
          Select-String -Path "build_XX\Makefile.Release" -Pattern "DESTDIR|TARGET" | ForEach-Object { $_.Line }

      # --- Compila ----------------------------------------------------------
      - name: Build (mingw32-make)
        shell: pwsh
        run: |
          cd build_XX
          mingw32-make -j4
          if ($LASTEXITCODE -ne 0) { throw "mingw32-make falhou" }

      # --- Copia DLLs Qt ----------------------------------------------------
      - name: Deploy Qt DLLs
        shell: pwsh
        run: |
          $qtbin = (Get-Command windeployqt.exe).Path
          $exe = Get-ChildItem -Path "build_XX\executables\SimulIDE_${{ env.APP_VER }}" -Filter "simulide.exe" -Recurse | Select-Object -First 1
          if (-not $exe) { throw "Nenhum simulide.exe encontrado" }
          & $qtbin $exe.FullName --no-angle --no-opengl-sw
          "FINAL_EXE=$($exe.FullName)" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host ">> windeployqt concluído"

      # --- Empacota ZIP -----------------------------------------------------
      - name: Package ZIP
        shell: pwsh
        run: |
          $zip = "SimulIDE-${{ env.APP_VER }}-win64-MinGW.zip"
          Compress-Archive -Path "build_XX\\executables\\SimulIDE_${{ env.APP_VER }}\\*" -DestinationPath $zip -Force
          "ZIP_NAME=$zip" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          Write-Host ">> ZIP pronto: $zip"

      # --- Artifact & Release -----------------------------------------------
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimulIDE-${{ env.APP_VER }}-win64-MinGW
          path: ${{ env.ZIP_NAME }}
          if-no-files-found: error

      - name: Publish GitHub Release
        if: ${{ startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && inputs.publish_release) }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.APP_VER }}
          files: ${{ env.ZIP_NAME }}
          generate_release_notes: true
