name: Windows MSVC Static (Qt5 one-exe) + Tag/Release

on:
  push:
    branches: [ "master" ]
    tags: [ "v*", "V*", "release-*" ]
  workflow_dispatch:
    inputs:
      version:
        description: "Versão (ex.: v2.0.0-RC1)"
        required: false
        type: string
      publish_release:
        description: "Publicar Release?"
        required: true
        default: true
        type: boolean

permissions:
  contents: write

jobs:
  qt-static-build:
    name: Build & Cache Qt 5.15.2 Static (MSVC)
    runs-on: windows-latest
    env:
      QT_VER: "5.15.2"
      QT_TRIPLET: "msvc2019_64"
      QT_SRC_ROOT: "C:\\qt-src\\5.15.2\\Src"
      QT_INSTALL_PREFIX: "C:\\qt-static\\5.15.2\\msvc2019_64-static"

    steps:
      - name: Setup MSVC (VS 2022, x64)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Restore Qt static cache
        id: cache-qt
        uses: actions/cache@v4
        with:
          path: "${{ env.QT_INSTALL_PREFIX }}"
          key: "qt5static-${{ env.QT_VER }}-${{ env.QT_TRIPLET }}-msvc2022-opengl-desktop-staticruntime-v1"

      - name: Install Python (for aqt) (if building qtbase)
        if: steps.cache-qt.outputs.cache-hit != 'true'
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # >>> PERL SEMPRE (necessário para syncqt dos módulos) <<<
      - name: Install Perl (required for Qt modules)
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: "5.32"

      - name: Install aqt
        run: |
          pip install "aqtinstall==3.1.*"

      - name: Ensure Qt sources present
        shell: pwsh
        run: |
          if (-not (Test-Path 'C:\qt-src\5.15.2\Src')) {
            python -m aqt install-src windows desktop 5.15.2 --outputdir 'C:\qt-src'
          }

      - name: Configure + Build + Install Qt (static + /MT) if not cached
        if: steps.cache-qt.outputs.cache-hit != 'true'
        shell: cmd
        env:
          QT_INSTALL_PREFIX: "C:\\qt-static\\5.15.2\\msvc2019_64-static"
          QT_SRC_ROOT: "C:\\qt-src\\5.15.2\\Src"
        run: |
          cd /d %QT_SRC_ROOT%\qtbase
          call configure.bat -prefix "%QT_INSTALL_PREFIX%" -platform win32-msvc ^
            -release -static -static-runtime -opensource -confirm-license ^
            -opengl desktop -nomake tests -nomake examples ^
            -no-icu -no-dbus -no-angle -mp
          nmake /NOLOGO
          nmake /NOLOGO install

      # Garante módulos SEMPRE; qtmultimedia é construído no subalvo 'multimedia.pro'
      - name: Ensure Qt modules (SVG, Multimedia, SerialPort)
        shell: cmd
        env:
          QT_INSTALL_PREFIX: "C:\\qt-static\\5.15.2\\msvc2019_64-static"
          QT_SRC_ROOT: "C:\\qt-src\\5.15.2\\Src"
        run: |
          @echo on
          setlocal EnableExtensions EnableDelayedExpansion
          set "QTDIR=%QT_INSTALL_PREFIX%"
          set "PATH=%QTDIR%\bin;%PATH%"
          where perl.exe >nul 2>&1 || ( echo ERROR: perl.exe not found in PATH & exit /b 2 )
      
          set "MOD_BUILD=C:\qt-build-mods"
          if not exist "%MOD_BUILD%" mkdir "%MOD_BUILD%"
      
          rem ==== qtsvg (src\src.pro) ====
          if not exist "%QTDIR%\lib\Qt5Svg.lib"  goto build_qtsvg
          if not exist "%QTDIR%\mkspecs\modules\qt_lib_svg.pri" goto build_qtsvg
          echo Qt5Svg present. Skipping qtsvg.
          goto check_qtmultimedia
          :build_qtsvg
          echo --- Building qtsvg ---
          if not exist "%MOD_BUILD%\qtsvg" mkdir "%MOD_BUILD%\qtsvg"
          cd /d "%MOD_BUILD%\qtsvg"
          set "QMAKEFEATURES=%QT_SRC_ROOT%\qtsvg\mkspecs\features"
          "%QTDIR%\bin\qmake.exe" -v
          dir /b "%QT_SRC_ROOT%\qtsvg\src"
          "%QTDIR%\bin\qmake.exe" "%QT_SRC_ROOT%\qtsvg\src\src.pro" -r
          if errorlevel 1 ( echo ERROR: qmake qtsvg failed & type config.log & exit /b 2 )
          nmake /NOLOGO || ( echo ERROR: nmake qtsvg failed & exit /b 2 )
          nmake /NOLOGO install || ( echo ERROR: nmake install qtsvg failed & exit /b 2 )
          if not exist "%QTDIR%\lib\Qt5Svg.lib" ( echo ERROR: Qt5Svg.lib missing & exit /b 2 )
          if not exist "%QTDIR%\mkspecs\modules\qt_lib_svg.pri" ( echo ERROR: qt_lib_svg.pri missing & exit /b 2 )
      
          :check_qtmultimedia
          rem ==== qtmultimedia (subtarget: src\multimedia\multimedia.pro) ====
          if not exist "%QTDIR%\lib\Qt5Multimedia.lib"  goto build_qtmultimedia
          if not exist "%QTDIR%\mkspecs\modules\qt_lib_multimedia.pri" goto build_qtmultimedia
          echo Qt5Multimedia present. Skipping qtmultimedia.
          goto check_qtserialport
          :build_qtmultimedia
          echo --- Building qtmultimedia (WMF + WASAPI) ---
          if not exist "%MOD_BUILD%\qtmultimedia-multimedia" mkdir "%MOD_BUILD%\qtmultimedia-multimedia"
          cd /d "%MOD_BUILD%\qtmultimedia-multimedia"
          set "QMAKEFEATURES=%QT_SRC_ROOT%\qtmultimedia\mkspecs\features"
          "%QTDIR%\bin\qmake.exe" -v
          dir /b "%QT_SRC_ROOT%\qtmultimedia\src\multimedia"
          rem Passa features e configs explicitamente
          "%QTDIR%\bin\qmake.exe" "%QT_SRC_ROOT%\qtmultimedia\src\multimedia\multimedia.pro" -r CONFIG+=wmf CONFIG+=wasapi
          if errorlevel 1 (
            echo ERROR: qmake qtmultimedia failed
            if exist config.log type config.log
            exit /b 2
          )
          nmake /NOLOGO || ( echo ERROR: nmake qtmultimedia failed & exit /b 2 )
          nmake /NOLOGO install || ( echo ERROR: nmake install qtmultimedia failed & exit /b 2 )
          if not exist "%QTDIR%\lib\Qt5Multimedia.lib" ( echo ERROR: Qt5Multimedia.lib missing after install & exit /b 2 )
          if not exist "%QTDIR%\mkspecs\modules\qt_lib_multimedia.pri" ( echo ERROR: qt_lib_multimedia.pri missing after install & exit /b 2 )
      
          :check_qtserialport
          rem ==== qtserialport (src\src.pro) ====
          if not exist "%QTDIR%\lib\Qt5SerialPort.lib"  goto build_qtserialport
          if not exist "%QTDIR%\mkspecs\modules\qt_lib_serialport.pri" goto build_qtserialport
          echo Qt5SerialPort present. Skipping qtserialport.
          goto list_installed
          :build_qtserialport
          echo --- Building qtserialport ---
          if not exist "%MOD_BUILD%\qtserialport" mkdir "%MOD_BUILD%\qtserialport"
          cd /d "%MOD_BUILD%\qtserialport"
          set "QMAKEFEATURES=%QT_SRC_ROOT%\qtserialport\mkspecs\features"
          "%QTDIR%\bin\qmake.exe" -v
          dir /b "%QT_SRC_ROOT%\qtserialport\src"
          "%QTDIR%\bin\qmake.exe" "%QT_SRC_ROOT%\qtserialport\src\src.pro" -r
          if errorlevel 1 ( echo ERROR: qmake qtserialport failed & type config.log & exit /b 2 )
          nmake /NOLOGO || ( echo ERROR: nmake qtserialport failed & exit /b 2 )
          nmake /NOLOGO install || ( echo ERROR: nmake install qtserialport failed & exit /b 2 )
          if not exist "%QTDIR%\lib\Qt5SerialPort.lib" ( echo ERROR: Qt5SerialPort.lib missing & exit /b 2 )
          if not exist "%QTDIR%\mkspecs\modules\qt_lib_serialport.pri" ( echo ERROR: qt_lib_serialport.pri missing & exit /b 2 )
      
          :list_installed
          echo ----- Present Qt libs -----
          dir /b "%QTDIR%\lib\Qt5*.lib"
          echo ----- Present Qt module PRIs -----
          dir /b "%QTDIR%\mkspecs\modules\qt_lib_*.pri"



  build-app:
    name: Build App (Static, One EXE) + Tag/Release
    needs: qt-static-build
    runs-on: windows-latest
    env:
      PRO_DIR: "build_XX"
      PRO_FILE: "SimulIDE_Build.pro"
      BUILD_DIR: "out_msvc"
      CONFIG: "release"
      QT_INSTALL_PREFIX: "C:\\qt-static\\5.15.2\\msvc2019_64-static"

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Setup MSVC (VS 2022, x64)
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: x64

      - name: Restore Qt static cache
        uses: actions/cache@v4
        with:
          path: "${{ env.QT_INSTALL_PREFIX }}"
          key: "qt5static-5.15.2-msvc2019_64-msvc2022-opengl-desktop-staticruntime-v1"

      - name: Compute version + optionally create tag
        id: ver
        uses: actions/github-script@v7
        with:
          script: |
            const ev = context.eventName;
            let ver = '';
            if (ev === 'workflow_dispatch' && core.getInput('version')) {
              ver = core.getInput('version');
            } else if (context.ref && context.ref.startsWith('refs/tags/')) {
              ver = context.ref.replace('refs/tags/','');
            } else {
              ver = `dev${context.runNumber}`;
            }
            ver = ver.replace(/[^0-9A-Za-z._-]/g, '');
            core.exportVariable('APP_VER', ver);
            core.info(`>> Versão: ${ver}`);
            if (ev === 'workflow_dispatch' && core.getInput('version')) {
              const tagRef = `refs/tags/${ver}`;
              try {
                await github.rest.git.getRef({ owner: context.repo.owner, repo: context.repo.repo, ref: tagRef });
                core.info(`Tag ${ver} já existe.`);
              } catch (e) {
                if (e.status === 404) {
                  const sha = context.sha;
                  await github.rest.git.createRef({ owner: context.repo.owner, repo: context.repo.repo, ref: tagRef, sha });
                  core.info(`Criada tag ${ver} em ${sha}`);
                } else {
                  throw e;
                }
              }
            }

      - name: Prepare build directory (out-of-source)
        shell: pwsh
        run: |
          if (-not (Test-Path $env:BUILD_DIR)) { New-Item -ItemType Directory -Path $env:BUILD_DIR | Out-Null }

      - name: Debug installed Qt modules
        shell: pwsh
        run: |
          Write-Host "Libraries in $env:QT_INSTALL_PREFIX\lib:"
          Get-ChildItem "$env:QT_INSTALL_PREFIX\lib" -Filter "Qt5*.lib" | Sort-Object Name | Select-Object -ExpandProperty Name
          Write-Host "`nModule PRIs in $env:QT_INSTALL_PREFIX\mkspecs\modules:"
          Get-ChildItem "$env:QT_INSTALL_PREFIX\mkspecs\modules" -Filter "qt_lib_*.pri" | Sort-Object Name | Select-Object -ExpandProperty Name

      - name: Force static CRT (/MT) in .pro (before qmake)
        shell: pwsh
        run: |
          $proPath = Join-Path $env:PRO_DIR $env:PRO_FILE
          if (-not (Test-Path $proPath)) { Write-Host "Aviso: $proPath não encontrado. Pulando reforço /MT."; exit 0 }
          Add-Content $proPath "QMAKE_CFLAGS_RELEASE += /MT`n"
          Add-Content $proPath "QMAKE_CXXFLAGS_RELEASE += /MT`n"
          Add-Content $proPath "QMAKE_LFLAGS_RELEASE += /NODEFAULTLIB:MSVCRT`n"

      - name: qmake (Static Release) using build_XX/SimulIDE_Build.pro
        shell: cmd
        env:
          QT_INSTALL_PREFIX: "C:\\qt-static\\5.15.2\\msvc2019_64-static"
        run: |
          set QTDIR=%QT_INSTALL_PREFIX%
          set PATH=%QTDIR%\bin;%PATH%
          set QMAKEPATH=%QTDIR%\mkspecs
          "%QTDIR%\bin\qmake.exe" -query
          dir /b "%QTDIR%\mkspecs\modules\qt_lib_*.pri"
          dir /b "%QTDIR%\lib\Qt5*.lib"
          cd %BUILD_DIR%
          "%QTDIR%\bin\qmake.exe" "%GITHUB_WORKSPACE%\%PRO_DIR%\%PRO_FILE%" -r -spec win32-msvc "CONFIG+=release static"

      - name: Build with nmake
        shell: cmd
        env:
          QT_INSTALL_PREFIX: "C:\\qt-static\\5.15.2\\msvc2019_64-static"
        run: |
          set QTDIR=%QT_INSTALL_PREFIX%
          set PATH=%QTDIR%\bin;%PATH%
          cd %BUILD_DIR%
          nmake /NOLOGO

      - name: Locate EXE (single-file) + Package ZIP
        id: out
        shell: pwsh
        run: |
          $exe = Get-ChildItem ".\${env:BUILD_DIR}" -Recurse -Filter *.exe -ErrorAction SilentlyContinue |
                 Sort-Object LastWriteTime -Descending | Select-Object -First 1
          if (-not $exe) {
            $exe = Get-ChildItem "$env:GITHUB_WORKSPACE" -Recurse -Filter *.exe -ErrorAction SilentlyContinue |
                   Sort-Object LastWriteTime -Descending | Select-Object -First 1
          }
          if (-not $exe) { throw "Nenhum .exe encontrado após o build." }
          "EXE=$($exe.FullName)" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          Write-Host "EXE encontrado: $($exe.FullName)"

          $zip = "SimulIDE-${env:APP_VER}-win64-MSVC-STATIC.zip"
          Compress-Archive -Path $exe.FullName -DestinationPath $zip -Force
          "ZIP_NAME=$zip" | Out-File -FilePath $env:GITHUB_OUTPUT -Append
          Write-Host "ZIP criado: $zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: SimulIDE-${{ env.APP_VER }}-win64-MSVC-STATIC
          path: "${{ steps.out.outputs.ZIP_NAME }}"
          if-no-files-found: error
          retention-days: 14

      - name: Publish GitHub Release
        if: startsWith(github.ref, 'refs/tags/') || (github.event_name == 'workflow_dispatch' && inputs.publish_release == true)
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.APP_VER }}
          files: "${{ steps.out.outputs.ZIP_NAME }}"
          generate_release_notes: true
